if(NOT SANYI_ROOT)
    get_filename_component(SANYI_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
set(SANYI_ROOT "${SANYI_ROOT}" CACHE INTERNAL "SanYi CAD project root")

set(SANYI_CMAKE_DIR         "${SANYI_ROOT}/CMake")
set(SANYI_UTILITY_DIR       "${SANYI_ROOT}/Utility/Utility")
set(SANYI_LOG_DIR           "${SANYI_ROOT}/Log/Log")
set(SANYI_CRASHHANDLER_DIR  "${SANYI_ROOT}/CrashHandler/CrashHandler")
set(SANYI_ENGINE_COMMON_DIR "${SANYI_ROOT}/Engine/Common")
set(SANYI_ENGINE_2D_DIR     "${SANYI_ROOT}/Engine/2D")
set(SANYI_ENGINE_3D_DIR     "${SANYI_ROOT}/Engine/3D")
set(SANYI_ENGINE_PERSISTENCE_DIR "${SANYI_ROOT}/Engine/Persistence")
# 以下 Render 路径已废弃，由 Renderx/RenderX 统一替代
# set(SANYI_RENDER_COMMON_DIR "${SANYI_ROOT}/Render/Common")
# set(SANYI_RENDER_2D_DIR     "${SANYI_ROOT}/Render/2D")
# set(SANYI_RENDER_3D_DIR     "${SANYI_ROOT}/Render/3D")
set(SANYI_RENDERX_DIR       "${SANYI_ROOT}/Renderx")
set(SANYI_GEOMODEL_DIR      "${SANYI_ROOT}/GeoModelCore/GeoModelCore")
set(SANYI_FILEIO_DIR        "${SANYI_ROOT}/FileIO/FileIO")
set(SANYI_UI_COMMON_DIR         "${SANYI_ROOT}/UI/Common")
set(SANYI_UI_2D_DIR             "${SANYI_ROOT}/UI/2D")
set(SANYI_UI_3D_DIR             "${SANYI_ROOT}/UI/3D")

set(SANYI_NETWORK_DIR       "${SANYI_ROOT}/Network/Network")
set(SANYI_NESTING_DIR       "${SANYI_ROOT}/Nesting/Nesting")
set(SANYI_PYTHONHOST_DIR    "${SANYI_ROOT}/PythonHost/PythonHost")
set(SANYI_THIRDPARTY_DIR    "${SANYI_ROOT}/ThirdParty")

set(SANYI_SOURCE_EXCLUDE_REGEX ".*\\.(bak|bak[0-9]|old|tmp|orig|save)$")
set(SANYI_HEADER_EXCLUDE_REGEX "${SANYI_SOURCE_EXCLUDE_REGEX}|.*~$")
